package projetobd.frames.relatorios;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import projetobd.App;
import projetobd.frames.Login;


public class RelatorioGeral extends javax.swing.JFrame {
    
    private static RelatorioGeral rgUnico;
    private int relatCont = 0;

    
    public static RelatorioGeral getRelatorioGeral(){
        if(rgUnico == null){
            rgUnico = new RelatorioGeral();
        }
        return rgUnico; 
    }
    /**
     * Creates new form RelatorioGeral
     */
    public RelatorioGeral() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_geral = new javax.swing.JTable();
        bt_cancel = new javax.swing.JButton();
        bt_confirm = new javax.swing.JButton();
        bt_inserir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbl_geral.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Autor", "Id Livro", "Id Genero", "Autor", "Livro", "Genero", "Data Lançamento", "ISBN", "Descrição"
            }
        ));
        tbl_geral.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(tbl_geral);
        if (tbl_geral.getColumnModel().getColumnCount() > 0) {
            tbl_geral.getColumnModel().getColumn(0).setPreferredWidth(50);
            tbl_geral.getColumnModel().getColumn(1).setPreferredWidth(50);
            tbl_geral.getColumnModel().getColumn(2).setPreferredWidth(60);
            tbl_geral.getColumnModel().getColumn(4).setPreferredWidth(150);
            tbl_geral.getColumnModel().getColumn(7).setPreferredWidth(130);
            tbl_geral.getColumnModel().getColumn(8).setPreferredWidth(500);
        }

        bt_cancel.setText("Cancel");
        bt_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cancelActionPerformed(evt);
            }
        });

        bt_confirm.setText("Gerar Relatório");
        bt_confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_confirmActionPerformed(evt);
            }
        });

        bt_inserir.setText("Inserir");
        bt_inserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_inserirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 962, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bt_inserir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_confirm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_cancel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_cancel)
                    .addComponent(bt_confirm)
                    .addComponent(bt_inserir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cancelActionPerformed
        // TODO add your handling code here:
        sair();
    }//GEN-LAST:event_bt_cancelActionPerformed

    private void bt_confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_confirmActionPerformed
        // TODO add your handling code here:
        listarGeral();
        
    }//GEN-LAST:event_bt_confirmActionPerformed

    private void bt_inserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_inserirActionPerformed
        // TODO add your handling code here:
        InsertView.getInsertView().setVisible(true);
    }//GEN-LAST:event_bt_inserirActionPerformed

    
    public void sair(){
        this.dispose();
    }
    
    public void listarGeral(){
        DefaultTableModel modelo = (DefaultTableModel) tbl_geral.getModel();
        modelo.setRowCount(0);
        App app = new App();
        app.setUser(Login.getFrameLogin().username);
        app.setPassword(Login.getFrameLogin().bdpassword);
        try  {
        	app.relatorioLivros(modelo);
        	        	
        } catch (SQLException e) {
        	System.out.println(e.getMessage());
        	JOptionPane.showMessageDialog(null, "Comando Invalido", "Transacao invalida", 2);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelatorioGeral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelatorioGeral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelatorioGeral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelatorioGeral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RelatorioGeral().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_cancel;
    private javax.swing.JButton bt_confirm;
    private javax.swing.JButton bt_inserir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_geral;
    // End of variables declaration//GEN-END:variables
}
