package projetobd.frames;

import projetobd.frames.deletes.DeleteLivro;
import projetobd.frames.inserts.InsertAutor;
import projetobd.frames.inserts.InsertGenero;
import projetobd.frames.relatorios.RelatorioAutores;
import projetobd.frames.relatorios.RelatorioGeral;
import projetobd.frames.updates.UpdateAutor;
import projetobd.frames.updates.UpdateGenero;


public class BD extends javax.swing.JFrame {

    private static BD bdUnico;
    /**
     * Creates new form BD
     */
    public BD() {
        initComponents();
    }
    
    public static BD getFrameBD(){
        if(bdUnico == null){
            bdUnico = new BD();
        }
        return bdUnico;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        inserir = new javax.swing.JMenu();
        insertAutor = new javax.swing.JMenuItem();
        insertGen = new javax.swing.JMenuItem();
        alterar = new javax.swing.JMenu();
        altAutor = new javax.swing.JMenuItem();
        altGen = new javax.swing.JMenuItem();
        delete = new javax.swing.JMenu();
        delLivro = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        relAutor = new javax.swing.JMenuItem();
        relLivro = new javax.swing.JMenuItem();

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        inserir.setText("Inserir...");

        insertAutor.setText("Autor");
        insertAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertAutorActionPerformed(evt);
            }
        });
        inserir.add(insertAutor);

        insertGen.setText("Gênero");
        insertGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertGenActionPerformed(evt);
            }
        });
        inserir.add(insertGen);

        jMenuBar1.add(inserir);

        alterar.setText("Alterar...");

        altAutor.setText("Autor");
        altAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altAutorActionPerformed(evt);
            }
        });
        alterar.add(altAutor);

        altGen.setText("Gênero");
        altGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altGenActionPerformed(evt);
            }
        });
        alterar.add(altGen);

        jMenuBar1.add(alterar);

        delete.setText("Remover");

        delLivro.setText("Livro");
        delLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delLivroActionPerformed(evt);
            }
        });
        delete.add(delLivro);

        jMenuBar1.add(delete);

        jMenu3.setText("Relatorio...");

        relAutor.setText("Autores");
        relAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relAutorActionPerformed(evt);
            }
        });
        jMenu3.add(relAutor);

        relLivro.setText("Livros");
        relLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relLivroActionPerformed(evt);
            }
        });
        jMenu3.add(relLivro);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 341, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 141, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertAutorActionPerformed
        // TODO add your handling code here:
        InsertAutor.getInsertAutor().setVisible(true);
        
    }//GEN-LAST:event_insertAutorActionPerformed

    private void delLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delLivroActionPerformed
        // TODO add your handling code here:
        DeleteLivro.getDeleteLivro().setVisible(true);
    }//GEN-LAST:event_delLivroActionPerformed

    private void relAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relAutorActionPerformed
        // TODO add your handling code here:
        RelatorioAutores.getRelAut().setVisible(true);
    }//GEN-LAST:event_relAutorActionPerformed

    private void relLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relLivroActionPerformed
        // TODO add your handling code here:
        RelatorioGeral.getRelatorioGeral().setVisible(true);
    }//GEN-LAST:event_relLivroActionPerformed

    private void insertGenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertGenActionPerformed
        // TODO add your handling code here:
        InsertGenero.getInsertGenero().setVisible(true);
    }//GEN-LAST:event_insertGenActionPerformed

    private void altAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altAutorActionPerformed
        // TODO add your handling code here:
        UpdateAutor.getUpdateAutor().setVisible(true);
    }//GEN-LAST:event_altAutorActionPerformed

    private void altGenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altGenActionPerformed
        // TODO add your handling code here:
        UpdateGenero.getUpdateGenero().setVisible(true);
    }//GEN-LAST:event_altGenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem altAutor;
    private javax.swing.JMenuItem altGen;
    private javax.swing.JMenu alterar;
    private javax.swing.JMenuItem delLivro;
    private javax.swing.JMenu delete;
    private javax.swing.JMenu inserir;
    private javax.swing.JMenuItem insertAutor;
    private javax.swing.JMenuItem insertGen;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem relAutor;
    private javax.swing.JMenuItem relLivro;
    // End of variables declaration//GEN-END:variables
}
